#!/bin/bash
#BSUB -q long
#BSUB -R "span[hosts=1]"
#BSUB -n 8
#BSUB -o %J.out
#BSUB -e %J.err
#BSUB -J co-hollow

#export I_MPI_ADJUST_REDUCE=3
#export MPIR_CVAR_COLL_ALIAS_CHECK=0

ulimit -s unlimited
source /data/home/phu/apps/Intel/2019/parallel_studio_xe_2019/psxevars.sh intel64
source /data/home/phu/apps/Intel/2019/profile.d/mpi_intelmpi-5.0.2.044.sh intel64
cd $LS_SUBCWD
NP=`echo $LSB_HOSTS | wc -w`

mpirun -n $NP /data/apps/vasp/vasp_std > print-out
